// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: 1.8_video

#include "ui.h"

void arcincrement(lv_event_t * e)
{
	// Your code here
}

void labelincrement(lv_event_t * e)
{
	// Your code here
}
